on:
#  workflow_dispatch:
#    inputs:
#      # Git ref of the duckdb repo
#      duckdb-ref:
#        required: true
#        type: string
  schedule:
    - cron: "0 5 * * 1"  # run every Monday day at 5AM

name: Vendor upstream DuckDB sources

jobs:
  vendor:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit.outputs.sha }}

    name: "Update vendored sources"
    if: github.repository == 'duckdb/duckdb-java'

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: duckdb/duckdb
          path: .git/duckdb
          fetch-depth: 0

      - name: Update docs
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            git rm -rf src/duckdb
            python vendor.py --duckdb .git/duckdb
            git add src/duckdb CMakeLists.txt
            rm -rf .git/duckdb
          COMMIT_MESSAGE: "Update vendored DuckDB sources to $REV"
          COMMIT_NAME: "DuckDB Labs GitHub Bot"
          COMMIT_EMAIL: "github_bot@duckdblabs.com"
          PR_BRANCH_NAME: "chore-update-docs-${PR_ID}"
          PR_TITLE: "chore: auto update docs"
          GITHUB_TOKEN: ${{ secrets.GH_UPDATE_DOCS_TOKEN }}
